name: Portfolio

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the Portfolio/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/Portfolio -v ${{ github.workspace }}/_site:/srv/Portfolio/_site \
        Portfolio/builder:latest /bin/bash -c "chmod -R 777 /srv/Portfolio && Portfolio build --future"
